repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write --ignore-unknown
        language: node
        types: [text]
        args: []
        require_serial: false
        additional_dependencies: ["prettier"]
